Update masscanAndLFTP.yml

diff --git a/.github/workflows/masscanAndLFTP.yml b/.github/workflows/masscanAndLFTP.yml
--- a/.github/workflows/masscanAndLFTP.yml
+++ b/.github/workflows/masscanAndLFTP.yml
@@ -23,14 +23,15 @@ jobs:
       run: | 
        echo "----------------------------------start scan"
       
-       #sudo masscan -p8983 4.4.119.0-4.4.119.255 --rate=1000000 |grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' || true >masscan.txt
-       #sudo masscan -p8983 4.4.119.0-4.4.119.255 --rate=1000000 |grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' || true >>masscan.txt
-       sudo masscan -p8983 4.4.119.0-4.4.119.255 --rate=1000000 |grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' || true | tee masscan.txt
+       sudo masscan -p8983 4.4.119.0-4.4.119.255 --rate=1000000 >masscan.txt
+       grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' masscan.txt>a.txt
        
        echo "----------------------------------ls"      
        ls
-       echo "----------------------------------show IPS"
+       echo "----------------------------------cat masscan.txt"
        cat masscan.txt
+       echo "----------------------------------a.txt"
+       cat a.txt
        #==================================================================LFTP
        #----------------------------------------install LFTP
     - name: install lftp
@@ -47,7 +48,7 @@ jobs:
 
          
         
-        
+# s7i7a sudo masscan -p8983 4.4.119.0-4.4.119.255 --rate=1000000 |grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' || true >masscan.txt        
 #sudo masscan --max-rate 100000000 -p 80 30.0.0.0-50.0.0.0 |grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
 #sudo masscan -p80,8000-8100 10.0.0.0/8 --rate=10000
 #  sudo masscan --max-rate 100000 -p 3389 30.0.0.0-50.0.0.0 |grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
